import fs from "fs";
import path from "path";
import {
  buildHeadMeta,
  buildLlmsTxt,
  buildNoscriptHtml,
  buildPrerenderHtml,
} from "../src/seo/generateArtifacts";
import { buildSchemaGraph } from "../src/seo/buildGraph";

const root = path.join(__dirname, "..");
const publicDir = path.join(root, "public");
const generatedDir = path.join(root, "src", "generated");

function getUtcDate() {
  return new Date().toISOString().slice(0, 10);
}

function replaceMarker(source: string, start: string, end: string, content: string) {
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  if (!pattern.test(source)) {
    throw new Error(`Missing markers ${start} ... ${end}`);
  }
  return source.replace(pattern, content);
}

function updateSitemap(dateModified: string) {
  const sitemapPath = path.join(publicDir, "sitemap.xml");
  const xml = fs.readFileSync(sitemapPath, "utf8");
  const updated = xml.replace(/<lastmod>[^<]*<\/lastmod>/, `<lastmod>${dateModified}</lastmod>`);
  fs.writeFileSync(sitemapPath, updated, "utf8");
}

function writeGeneratedMeta(dateModified: string) {
  fs.mkdirSync(generatedDir, { recursive: true });
  const contents = `// Generated by scripts/generate-seo-artifacts.ts — do not edit manually.
export const SEO_DATE_MODIFIED = "${dateModified}";
export const SEO_GOOGLE_VERIFICATION = ${JSON.stringify(process.env.GOOGLE_SITE_VERIFICATION || "")};
`;
  fs.writeFileSync(path.join(generatedDir, "seo-meta.ts"), contents, "utf8");
}

function patchIndexHtml(dateModified: string) {
  const templatePath = path.join(publicDir, "index.template.html");
  const indexPath = path.join(publicDir, "index.html");
  let html = fs.readFileSync(templatePath, "utf8");
  const criticalCss = fs.readFileSync(path.join(publicDir, "critical.css"), "utf8").trim();

  html = replaceMarker(
    html,
    "<!-- @critical-css-start -->",
    "<!-- @critical-css-end -->",
    `<style id="critical-css">${criticalCss}</style>`,
  );

  html = replaceMarker(
    html,
    "<!-- @seo-head-start -->",
    "<!-- @seo-head-end -->",
    buildHeadMeta(dateModified, process.env.GOOGLE_SITE_VERIFICATION || ""),
  );

  html = replaceMarker(
    html,
    "<!-- @seo-schema-start -->",
    "<!-- @seo-schema-end -->",
    `    <script type="application/ld+json">${JSON.stringify(buildSchemaGraph(dateModified))}</script>`,
  );

  html = replaceMarker(
    html,
    "<!-- @seo-noscript-start -->",
    "<!-- @seo-noscript-end -->",
    buildNoscriptHtml(),
  );

  html = replaceMarker(
    html,
    "<!-- @seo-prerender-start -->",
    "<!-- @seo-prerender-end -->",
    buildPrerenderHtml(),
  );

  fs.writeFileSync(indexPath, html, "utf8");
}

function main() {
  const dateModified = getUtcDate();

  writeGeneratedMeta(dateModified);
  fs.writeFileSync(path.join(publicDir, "llms.txt"), buildLlmsTxt(dateModified), "utf8");
  updateSitemap(dateModified);
  patchIndexHtml(dateModified);

  console.log(`SEO artifacts generated for ${dateModified}`);
}

main();